/* Header file for New Image project */
/* Compiles under Borland C, Djgpp C, and Linux */

#ifdef __TURBOC__
# ifndef __FLAT__
#   define _HUGE huge
#   define _MALLOC farmalloc
# else
#   define _HUGE
#   define _MALLOC malloc
# endif
#else
# define _HUGE
# define _MALLOC malloc
#endif

#include <inttypes.h>


//#define GUI

/* colors[] holds the user interface colours only - frames, text, the cursor,
 * the map background.  Data colours do not come from here: every product has
 * a 256 entry table of its own, loaded from config/palettes/<name>.pal (see
 * palette.c).  Do not grow this to make room for data levels. */
#define NUM_COLORS 16        /* number of custom reserved colors */
#define MaxFiles 200000        /* max files in directory */
#define MaxPorts 99
/* room for every product bufr2wrk.py writes: 16 reflectivity levels, 10
 * differential reflectivity, 10 velocity, 5 precipitation sums, echo tops,
 * phenomena and the rain rate.  One more slot than that is needed in the
 * unzip pass, for header.wrk. */
#define MaxNoMaps 64

/* One bit per port.  Up to 63 ports fitted in a 64 bit word; beyond that the
 * mask needs a wider type, and gcc's __int128 carries 128 of them. */
typedef unsigned __int128 port_mask;
#define PORT_BIT(p)  ((port_mask)1 << (p))
#define PORT_ALL     (~(port_mask)0)

/* Which products read_files() should bother with.  MaxNoMaps is 64, so one
 * word covers them, and the default is all of them - the viewer wants every
 * product because the user can switch to any of them without another read.
 * A caller after one thing does not: a vertical section needs the levels of
 * one family and nothing else, and unzipping and mosaicking the other forty
 * costs ten times what the family costs.  See want_maps in files.c. */
typedef unsigned long long map_mask;
#define MAP_BIT(m)   ((map_mask)1 << (m))
#define MAP_ALL      (~(map_mask)0)

#define MAX_Y 16
#define MAX_X 69
#define T_CHARS 8

#define STORM_X 60
#define STORM_Y 13
#define cof 6
#define Rsv 150
#define Rst 160
/* One identifier per map file bufr2wrk.py can write.  MAP_0..MAP_15 are the
 * constant altitude reflectivity levels (4_dbz_N.wrk), MAP_D* the differential
 * reflectivity levels (4_dif_N.wrk) and MAP_V* the radial velocity levels
 * (4_vel_N.wrk); the rest are one of a kind. */
typedef enum map_types {
 MAP_0,  MAP_1,  MAP_2,  MAP_3,  MAP_4,  MAP_5,  MAP_6,  MAP_7,
 MAP_8,  MAP_9,  MAP_10, MAP_11, MAP_12, MAP_13, MAP_14, MAP_15,
 MAP_H,  MAP_S,  MAP_P,
 MAP_Q1, MAP_Q3, MAP_Q6, MAP_Q12, MAP_Q24,
 MAP_D1, MAP_D2, MAP_D3, MAP_D4,  MAP_D5,
 MAP_D6, MAP_D7, MAP_D8, MAP_D9,  MAP_D10,
 MAP_V1, MAP_V2, MAP_V3, MAP_V4,  MAP_V5,
 MAP_V6, MAP_V7, MAP_V8, MAP_V9,  MAP_V10
} map_type;
#define MAP_Q MAP_Q1        /* the sum the readout column shows */

/* What kind of quantity a map holds.  It picks the palette, the readout
 * formatting and how overlapping radars are combined. */
typedef enum product_families {
 FAM_DBZ, FAM_RAIN, FAM_SUM, FAM_ZDR, FAM_VEL, FAM_HEIGHT, FAM_PHENOM,
 FAM_COUNT
} product_family;

/* How two radars covering one point are merged.
 *   MERGE_IDW  - inverse distance weighted in Z, for reflectivity and the
 *                quantities derived from it.  Averaging is meaningful there.
 *   MERGE_MAX  - the stronger reading wins: echo tops, phenomena codes.
 *   MERGE_NEAR - the nearer radar wins.  Averaging a Doppler velocity or a
 *                ZDR from two look directions produces a number that means
 *                nothing, so pick one instead. */
enum merge_mode { MERGE_IDW, MERGE_MAX, MERGE_NEAR };

struct map_info {
	map_type mapid;
	char *filename;
	char *palette;     /* config/palettes/<palette>.pal */
	char *descr;       /* cp866 title, drawn over the legend */
	product_family family;
	int level;         /* altitude/section number, 0 when there is none */
	unsigned char nodata;  /* the byte this product uses for "no data" */
	int nodata_alt;        /* previous marker, remapped on load; -1 when none */
	int noecho;            /* ... and for "no echo", -1 when it has none */
	unsigned char merge;   /* enum merge_mode */
	float mapres;      /* init by read_files() */
	unsigned char *bufhead;   /* init by init_files() */
	unsigned char *bufdata;   /* init by init_files() */
};

/* Colour table for one product, generated by mkpalettes.py from the pycao
 * palettes.  rgb[] is indexed by the .wrk byte, so it needs no thresholds at
 * run time; row[] is the legend, strongest band first, and lut_row[] says
 * which legend row a byte falls in - that is how a reading gets a label. */
#define PAL_MAX_LEGEND 24
#define PAL_LABEL      12

struct pal_row {
	unsigned char rgb[3];
	char label[PAL_LABEL+1];
};

struct palette {
	char name[24];
	char units[12];
	int  nodata;             /* byte meaning "no data" */
	int  noecho;             /* byte meaning "no echo", -1 when there is none */
	unsigned char rgb[256][3];
	unsigned char lut_row[256];
	int  rows;
	struct pal_row row[PAL_MAX_LEGEND];
};

extern struct palette current_palette;
extern int  load_palette(const char *dir,const char *name,struct palette *out);
extern void set_palette(const char *name,int nodata);  /* loads it, fills clev[] */
extern void draw_legend(const char *title);
extern void palette_rect(int *x,int *y,int *w,int *h);
extern const char *palette_label(int value);   /* legend label for a byte */
extern const char *palette_nodata_label(void);
extern const char *palette_label_of(const char *name,int value);

/* The ZDR byte scale, in one place: it wraps, and every reader of a ZDR byte
 * has to wrap it the same way or a cell prints one value and is painted
 * another.  See the comment on zdr_value() in palette.c. */
extern float zdr_value(int byte);
extern int   zdr_byte(float value);

/* Synthetic key code: KEY_PRODUCT+i selects maps[i].  The Qt panel uses it to
 * reach products that have no letter of their own. */
#define KEY_PRODUCT 0x2000
extern int no_maps;
extern int map_present(int index);    /* the current file carries this map */
extern int select_product(int key);   /* 1 when the key named a product */
/* map_value() takes DOUBLED coordinates - the display grid the cursor moves
 * over, twice MSIZE_int each way; get_map_data() halves them again.  To read
 * the data itself use map_grid(), which hands over the grid as it is. */
extern int map_value(map_type id,int xcoord,int ycoord);  /* -1 when absent */
extern int map_grid(map_type id,unsigned char *out);      /* side, or 0 */

extern int current_map,cur_file;
extern struct map_info maps[];
extern char grfdir[],mapdir[],cfgdir[];
extern float LC,BC,LU,BU;
extern unsigned char header[128];
extern char current_prefix;
extern unsigned int MSIZE;
extern float MPIX;
extern int masx[MaxPorts],masy[MaxPorts];
/* this radar's header was read for the current frame - see files.c.  Not
 * the same as "has a name": a nameless radar still carries data. */
extern unsigned char port_seen[MaxPorts];
extern unsigned char _HUGE *mapbuffer;
extern float L0[MaxPorts],B0[MaxPorts];
extern void init_maps(void);
extern int  map_index(map_type id);
extern void init_files(void);
extern void de_init_files(void);
extern void set_cur_map(map_type id);
extern void read_files(int map_number,int flag);
extern void read_cfg(char *wrk_path,char *image_cfg);
extern int get_map_data(map_type id,int xcoord,int ycoord);

extern void showtime(void);
extern void showdata(int xcoord,int ycoord);   /* mapbuffer cell, not offset */
extern void surface_to_map(int x,int y,int *mx,int *my);
extern void show_header(void);

extern int current_color;

extern int WINDOW_XSIZE,WINDOW_YSIZE,WINDOW_LEFT,WINDOW_UP;

#define MIN_MAP_SIZE 200   /* smallest sensible map area, in pixels */
extern void update_coords(void);
extern void message_loop(void);
extern int message_poll(void);
extern int init_graph(char *palette_file);
extern int batch_cross;    /* cross=... : the batch surface has to fit vert() */
extern void close_graph(void);
extern int draw_map(int vectors);
extern void outtextxy(int x,int y,char *text);
extern void my_circle(int x_center,int y_center,int radius);
extern void my_pixel(int x,int y);
extern void my_line(int x1,int y1,int x2,int y2);
extern void my_poly(int numpoints,int  polypoints[]);
extern void my_textxy(int x_begin,int y_begin,char text[]);
extern void solid_bar(int x1,int y1,int x2,int y2,int color);

#define RAD   M_PI/180.
#define GR    180./M_PI

extern void convert(float LA,float BA,float X,float Y,float *Lar,float *Fir);
extern void convert_port(float LA,float BA,float X,float Y,float *Lar,float *Fir);
extern void conv_back(float LA,float BA,float Lar,float Fir,float *X,float *Y);
extern unsigned char *get_ptr(float LN,float BN,float MapRes,int size_from,int size_to);
extern void koord(unsigned char *tb,unsigned char *tbl_ptr, unsigned int size_from,int port);
extern void walk_table_max(unsigned char *tb,unsigned char *ntb,unsigned char *tbl_ptr,unsigned int size_from,unsigned int size_to,int nodata);
extern void walk_table_idw(unsigned char *tb,unsigned char *ntb,unsigned char *tbl_ptr,unsigned int size_from,unsigned int size_to,float MapRes,int port,int,int nodata);
extern void walk_table_near(unsigned char *tb,unsigned char *ntb,unsigned char *tbl_ptr,unsigned int size_from,unsigned int size_to,float MapRes,int port,int,int nodata);
extern void interpolation (unsigned char *ntb,int map_size,int nodata,int noecho,int smooth,int wrapped);
extern void expand(unsigned char *in,unsigned char _HUGE *out,int mapsize);
extern void expand_rect(unsigned char *in,unsigned char _HUGE *out,int w,int h);
extern void expand_heights(unsigned char *in,unsigned char _HUGE *out,int mapsize);
struct info {
  short type;
  short x1,x2,y1,y2;
  unsigned int size;
  void *ptr;
};

#define MaxTLO 3000

void draw_tlo(struct info inf_ptr[],int max_number);
void set_cur_geogr(int number);

extern struct    info *grafs;
extern int       max_grafs;

extern int move_file(char *from,char *to);
extern void read_dir(void);
/* "YYMMDD": read_dir() ignores older frames.  Empty = the whole archive. */
extern char archive_since[8];

struct MyFile {                             /* For an archive */
  unsigned char FileYear;
  unsigned char FileMonth;
  unsigned char FileDay;
  unsigned char FileHour;
  unsigned char FileMinute;
  port_mask flag;
};
extern struct MyFile Files[MaxFiles];
extern int FilesRead;

extern int              Second;
extern char             in_dir[MaxPorts][100];

/* Callback functions */
extern int              key_pressed(int key);
extern void mouse_move(int x,int y);
extern int  mouse_click_left(int x,int y);
extern void mouse_dclick_left(int x, int y);
extern int  mouse_click_right(int x,int y);
extern void timer(void);


typedef struct save {
        void *context;
        int x1,y1,x2,y2;
        int was_cursor;
        void *new_cursor;
} win_save;


win_save *OpenWindow(int CoordX,int CoordY,int SizeX,int SizeY,char *Header,int HeaderColor);
void CloseWindow(win_save *SavePtr);
void MoveCursor(win_save *SavePtr,int x,int y);
void HideCursor(win_save *SavePtr);
int GetWindowKey(void);

extern int save_geotiff(const char *path);   /* geotiff.c */
extern int save_info(const char *path);      /* geotiff.c, JSON metadata */
extern int archive(void);
extern int anim_begin,anim_end;
extern int anim_running,anim_stopped;

#define CharXSize 8
#define CharYSize 16

extern void ViewString(int x,int y,int size_x,int size_y,char *line[]);

extern void ViewForecast(int number);

extern port_mask show_maps;
extern map_mask  want_maps;   /* which products read_files() loads */
extern map_mask  head_maps;   /* ... and which only for their passport */


extern unsigned int MSIZE_int;
extern long clev[256];
extern int y_up,x_left,xck,yck,xc1,yc1,xc2,yc2;
extern int xco,yco,xco1,xco2,yco1,yco2;
extern int flagl,flagv,flags,flago,flaga,fp;
extern float MRES,BW,HMRL[MaxPorts];
extern float SPEED[MaxPorts],W[MaxPorts][MaxNoMaps];
extern signed int AZIMUT[MaxPorts],R[MaxPorts];
extern char ST[MaxPorts][50];
extern void set_cur_prefix(int cur_file,char prefix);
extern void vert(int x1,int y1,int x2,int y2);
extern int fk[MaxNoMaps][MaxPorts];

extern int getch(void);