/* palette.c - per product colour tables and the legend column.
 *
 * The viewer used to colour a map through config/palette (16 RGB triples) and
 * a config/thresh.<x> file that mapped at most 15 data levels onto them.  That
 * was the whole colour budget: reflectivity, echo tops and rainfall all shared
 * those 15 steps, and there was no room for a product that needed more.
 *
 * A product now carries a table of its own, config/palettes/<name>.pal,
 * generated by mkpalettes.py from the same pycao palettes the web side uses.
 * It gives a colour for every one of the 256 possible .wrk bytes, so the data
 * levels are limited by the byte, not by the palette.  config/palette is still
 * read, for the user interface colours in colors[] - frames, text, the map
 * background - and 16 of those is plenty.
 */

#include <grx20.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "image.h"

extern long colors[NUM_COLORS];
extern FILE *logfile;

long clev[256];                  /* .wrk byte -> GrColor, for draw_line() */
struct palette current_palette;

/* Geometry of the legend column, to the left of the map.  The title sits at
 * LEG_TOP, the units under it, then one row per band. */
#define LEG_LEFT   0             /* left edge on the surface        */
#define LEG_TOP    100           /* below the clock and the date    */
#define LEG_WIDTH  94            /* the map starts at WINDOW_LEFT   */
#define LEG_SWATCH 9             /* colour box, width and height    */
#define LEG_PITCH  12            /* box plus the gap under it       */
#define LEG_FIRST  (LEG_TOP+30)  /* first row: title and units above */

void palette_rect(int *x,int *y,int *w,int *h)
{
   *x = LEG_LEFT;
   *y = 0;                                     /* clock and date sit above */
   *w = WINDOW_LEFT;                           /* everything left of the map */
   *h = LEG_FIRST + PAL_MAX_LEGEND*LEG_PITCH + 4;
}

/* ------------------------------------------------------------------ */
/* reading a .pal file                                                 */
/* ------------------------------------------------------------------ */

/* Copy the part of a legend line after the ':' into a fixed field. */
static void copy_label(char *dst,const char *src)
{
   const char *colon = strchr(src,':');
   int i = 0;

   if (colon == NULL) { dst[0] = 0; return; }
   colon++;
   while (i < PAL_LABEL && colon[i] && colon[i] != '\n' && colon[i] != '\r') {
      dst[i] = colon[i];
      i++;
   }
   while (i > 0 && dst[i-1] == ' ') i--;       /* trailing pad, if any */
   dst[i] = 0;
}

/* Read one word after the keyword, e.g. "units dBZ" -> "dBZ".  The value may
 * be empty (the phenomena palette has no unit), which sscanf cannot report. */
static void copy_word(char *dst,int size,const char *line,const char *keyword)
{
   const char *p = line + strlen(keyword);
   int i = 0;

   while (*p == ' ' || *p == '\t') p++;
   while (i < size-1 && p[i] && p[i] != '\n' && p[i] != '\r' && p[i] != ' ') {
      dst[i] = p[i];
      i++;
   }
   dst[i] = 0;
}

int load_palette(const char *dir,const char *name,struct palette *out)
{
   char path[200],line[200];
   FILE *file;
   int expected,got,i;

   sprintf(path,"%s/palettes/%s.pal",dir,name);
   if ((file = fopen(path,"rt")) == NULL) {
      fprintf(logfile,"cannot open palette %s\n",path);
      return 0;
   }

   memset(out,0,sizeof(*out));
   out->nodata = 254;
   out->noecho = -1;
   strncpy(out->name,name,sizeof(out->name)-1);

   while (fgets(line,sizeof(line),file) != NULL) {
      if (line[0] == '#' || line[0] == '\n') continue;

      if (!strncmp(line,"units ",6))
         copy_word(out->units,sizeof(out->units),line,"units");
      else if (!strncmp(line,"nodata ",7))
         sscanf(line,"nodata %d",&out->nodata);
      else if (!strncmp(line,"noecho ",7))
         sscanf(line,"noecho %d",&out->noecho);
      else if (!strncmp(line,"colors ",7)) {
         sscanf(line,"colors %d",&expected);
         for (i = 0; i < expected; i++) {
            int index,r,g,b,row;
            if (fgets(line,sizeof(line),file) == NULL) break;
            if (sscanf(line,"%d %d %d %d %d",&index,&r,&g,&b,&row) != 5) break;
            if (index < 0 || index > 255) continue;
            out->rgb[index][0] = r;
            out->rgb[index][1] = g;
            out->rgb[index][2] = b;
            out->lut_row[index] = (row >= 0 && row < PAL_MAX_LEGEND) ? row : 0;
         }
         if (i != expected) {
            fprintf(logfile,"%s: %d colour rows, expected %d\n",path,i,expected);
            fclose(file);
            return 0;
         }
      }
      else if (!strncmp(line,"legend ",7)) {
         sscanf(line,"legend %d",&expected);
         got = expected < PAL_MAX_LEGEND ? expected : PAL_MAX_LEGEND;
         for (i = 0; i < got; i++) {
            int r,g,b;
            if (fgets(line,sizeof(line),file) == NULL) break;
            if (sscanf(line,"%d %d %d",&r,&g,&b) != 3) break;
            out->row[i].rgb[0] = r;
            out->row[i].rgb[1] = g;
            out->row[i].rgb[2] = b;
            copy_label(out->row[i].label,line);
         }
         out->rows = i;
         if (expected > PAL_MAX_LEGEND)
            fprintf(logfile,"%s: %d legend rows, showing the first %d\n",
                    path,expected,PAL_MAX_LEGEND);
      }
   }
   fclose(file);

   if (out->rows == 0) {
      fprintf(logfile,"%s: no legend\n",path);
      return 0;
   }
   return 1;
}

/* ------------------------------------------------------------------ */
/* installing one                                                      */
/* ------------------------------------------------------------------ */

/* GrAllocColor is not free - in a palette mode it consumes a hardware entry -
 * and a 256 entry table holds at most two dozen distinct colours, so allocate
 * each colour once and hand the previous product's back on the way out. */
static long allocated[PAL_MAX_LEGEND+2];
static int  allocated_count;
static long legend_color[PAL_MAX_LEGEND];   /* swatch colour per legend row */

static long alloc_cached(int r,int g,int b,
                         unsigned char seen[][3],long value[],int *count)
{
   int i;

   for (i = 0; i < *count; i++)
      if (seen[i][0] == r && seen[i][1] == g && seen[i][2] == b)
         return value[i];

   if (*count >= PAL_MAX_LEGEND+2)             /* more colours than a legend */
      return GrAllocColor(r,g,b);              /* can hold: just allocate it */

   seen[*count][0] = r;
   seen[*count][1] = g;
   seen[*count][2] = b;
   value[*count] = GrAllocColor(r,g,b);
   return value[(*count)++];
}

/* `nodata` is the map's own no-data byte, which need not be the palette's:
 * 4_dbz_0.wrk is drawn with the reflectivity palette but marks a missing point
 * with 221, not 254 (see the maps[] table).  Paint that byte as no data
 * whatever the file says, so the product's marker always wins. */
void set_palette(const char *name,int nodata)
{
   static char loaded[24] = "";
   static int  loaded_nodata = -1;
   unsigned char seen[PAL_MAX_LEGEND+2][3];
   long value[PAL_MAX_LEGEND+2];
   int count = 0;
   int i;

   if (!strcmp(loaded,name) && loaded_nodata == nodata) return;

   /* into a copy first: load_palette clears what it is given, and a failure
    * halfway through must not leave the palette on screen half erased */
   {
      struct palette wanted;

      if (!load_palette(grfdir,name,&wanted)) {
         if (loaded[0]) return;                /* keep the one that works */
         fprintf(logfile,"no usable palette - check %s/palettes\n",grfdir);
         exit(3);
      }
      current_palette=wanted;
   }

   if (nodata >= 0 && nodata <= 255) {
      int row = current_palette.rows-1;         /* no data is always last */

      current_palette.nodata = nodata;
      current_palette.lut_row[nodata] = row;
      current_palette.rgb[nodata][0] = current_palette.row[row].rgb[0];
      current_palette.rgb[nodata][1] = current_palette.row[row].rgb[1];
      current_palette.rgb[nodata][2] = current_palette.row[row].rgb[2];
   }

   for (i = 0; i < allocated_count; i++) GrFreeColor(allocated[i]);
   allocated_count = 0;

   for (i = 0; i < 256; i++) {
      clev[i] = alloc_cached(current_palette.rgb[i][0],
                             current_palette.rgb[i][1],
                             current_palette.rgb[i][2],
                             seen,value,&count);
      /* every legend row has at least one byte pointing at it, which is where
       * the swatch colour comes from - no second allocation */
      legend_color[current_palette.lut_row[i]] = clev[i];
   }

   for (i = 0; i < count; i++) allocated[i] = value[i];
   allocated_count = count;

   strcpy(loaded,name);
   loaded_nodata = nodata;
}

const char *palette_label(int value)
{
   int row;

   if (value < 0 || value > 255) value = current_palette.nodata;
   row = current_palette.lut_row[value];
   if (row >= current_palette.rows) row = current_palette.rows-1;
   return current_palette.row[row].label;
}

/* The label for a byte the map has no reading for.  The generator always puts
 * that row last, so the readout can name it without a lookup. */
const char *palette_nodata_label(void)
{
   if (current_palette.rows == 0) return "";
   return current_palette.row[current_palette.rows-1].label;
}

/* Label from a palette other than the one on screen: the readout column lists
 * every level of every product, each in its own scale.  It runs on every mouse
 * motion and walks several palettes each time, so keep a few of them around
 * rather than reading a file per line. */
#define PAL_CACHE 6

const char *palette_label_of(const char *name,int value)
{
   static struct palette cache[PAL_CACHE];
   static int filled,next;
   int i,row;

   for (i = 0; i < filled; i++)
      if (!strcmp(cache[i].name,name)) break;

   if (i == filled) {
      i = filled < PAL_CACHE ? filled : next;
      if (!load_palette(grfdir,name,&cache[i])) {
         cache[i].name[0] = 0;
         return "";
      }
      if (filled < PAL_CACHE) filled++;
      else next = (next+1)%PAL_CACHE;
   }

   if (value < 0 || value > 255) return "";
   row = cache[i].lut_row[value];
   if (row >= cache[i].rows) row = cache[i].rows-1;
   return cache[i].row[row].label;
}

/* ------------------------------------------------------------------ */
/* drawing the legend                                                  */
/* ------------------------------------------------------------------ */

void draw_legend(const char *title)
{
   int i,y;

   GrFilledBox(LEG_LEFT,LEG_TOP,LEG_LEFT+LEG_WIDTH,
               LEG_FIRST+PAL_MAX_LEGEND*LEG_PITCH+2,colors[0]);

   outtextxy(LEG_LEFT,LEG_TOP,(char *)title);
   if (current_palette.units[0])
      outtextxy(LEG_LEFT,LEG_TOP+14,current_palette.units);

   for (i = 0; i < current_palette.rows; i++) {
      y = LEG_FIRST + i*LEG_PITCH;
      GrFilledBox(LEG_LEFT,y,LEG_LEFT+LEG_SWATCH,y+LEG_SWATCH,legend_color[i]);
      GrBox(LEG_LEFT,y,LEG_LEFT+LEG_SWATCH,y+LEG_SWATCH,colors[15]);
      outtextxy(LEG_LEFT+LEG_SWATCH+4,y-2,current_palette.row[i].label);
   }
}
